### ISSUE TITLE
Readme does not work for the latest Aurelia / style-loader

### ISSUE THREAD

**Issue by euglv** [jbockle/aurelia-useable-style-loader#1]
The following link in readme is broken: https://github.com/webpack-contrib/style-loader#useable
The following `webpack.config.js` does not work any more:
```
{
  module: {
    rules: [
      {
        test: /\.css$/,
        use: ['style-loader/useable', 'css-loader']
      }
    ]
  }
}
```

But the following works:
```
{
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader', options: { injectType: 'lazyStyleTag' } },
          'css-loader',
        ]
      }
    ]
  }
}
```

**Comment by euglv** [comment]
New style-loader documentation link: https://github.com/webpack-contrib/style-loader#lazystyletag

**Comment by jbockle** [comment]
thanks looks like style-loader is 1.0.0 now I'll get the updates in
