### ISSUE TITLE
Is there any way to preserve styles order?

### ISSUE THREAD

**Issue by euglv** [jbockle/aurelia-useable-style-loader#4]
For example, if I have Aurelia application with router and such `a.html`:
```
<template>
  <require from="./a.css">
  <require from="./common.css">
...
</template>
```
And the following `b.html`:
```
<template>
  <require from="./b.css">
  <require from="./common.css">
...
</template>
```
If I open Aurelia application for the first time when the page `a` or `b` is active - the page is displayed correctly, `common.css` styles are added last to the head.
But if I first open page `a` and then navigate to the page `b` - `common.css` styles will appear in head before `b.css` and styles became broken. 
When I navigate from page `a` to page `b` then styles related to `a.css` are removed from the head, and `b.css` styles are appended to the head, `common.css` styles remains at the same place.

**Comment by jbockle** [comment]
with this plugin no, however you can pair this with webpack loader rules to control where the style is inserted: https://webpack.js.org/loaders/style-loader/#insert

i.e. use a naming convention for your css files "like common.head.css, a.body.css, b.body.css"and have test expressions with different loaders rules for it.
```js
      {
        test: /\.head\.css$/,
        use: [{ loader: 'style-loader', options: { injectType: 'lazyStyleTag', } }, 'css-loader']
      },
      {
        test: /\.body\.css$/,
        use: [{ loader: 'style-loader', options: { injectType: 'lazyStyleTag', insert: 'body' } }, 'css-loader'] // has 'insert' option to place css inside <body>
      }
```
